#include <stdio.h>

#include <iostream>
#include <random>

int main() {
  std::random_device rd;  // Will be used to obtain a seed for the random number engine
  std::mt19937 mt(rd());  // Standard mersenne_twister_engine seeded with rd()
  std::uniform_int_distribution<int> distrib(0, 255);

  // Use distrib to transform the random unsigned int
  // generated by gen into an int in [0, 255]
  for(;;) {
    std::cout << distrib(mt) << std::endl;
    fgetc(stdin);
  }
}
